### ISSUE TITLE
need to specify python version and tensorflow version

### ISSUE THREAD

**Issue by jieyu-tech** [CLUEbenchmark/CLUE#1]
When running albert/run_classifier_inews.sh， I got this error:

AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer‘

I guess this is caused by Tensorflow version, I'm using tensorflow 2.0. However, I don't know exactly which version used in the example codes.

**Comment by jieyu-tech** [comment]
python version is 3.x, 3.7 is ok
Tensorflow is about 1.15

**Comment by brightmart** [comment]
yeah. we will add.
