### ISSUE TITLE
阅读理解执行报错

### ISSUE THREAD

**Issue by kingerious** [CLUEbenchmark/CLUE#110]
执行阅读理解脚本run_mrc_cmrc2018.sh ，会报：NotFoundError: /Users/git/CLUE/baselines/models_pytorch/mrc_pytorch/check_points/prev_trained_model/roberta_wwm_ext_base/bert_config.json
查看代码似乎没有创建这样的文件和目录。源代码里也没有找到这样的文件和目录

**Comment by ewrfcas** [comment]
mrrc_pytorch下的README有解释，先下载对应权重（roberta_wwm_ext_large应该是哈工大的git上有）然后放到指定目录后转化模型

**Comment by kingerious** [comment]
> mrrc_pytorch下的README有解释，先下载对应权重（roberta_wwm_ext_large应该是哈工大的git上有）然后放到指定目录后转化模型

谢谢~
