### ISSUE TITLE
CMRC2018 数据样本数对不上

### ISSUE THREAD

**Issue by choosewhatulike** [CLUEbenchmark/CLUE#119]
CMRC2018 的 test 集，[论文](https://arxiv.org/pdf/2004.05986.pdf)里的 Table 1 写的是 4.9k 样本数，本项目 README 里写的 1,002 个样本，而实际下载下来的[数据集 ](https://storage.googleapis.com/cluebenchmark/tasks/cmrc2018_public.zip)“test.json" 中是 2000 个样本。感觉是不是给的数据版本不太对，请问以哪个为准呢？

**Comment by brightmart** [comment]
以实际下载下来的为准，
