### ISSUE TITLE
数据集无法下载

### ISSUE THREAD

**Issue by yang9112** [CLUEbenchmark/CLUE#3]
目前脚本提供的地址都是google的地址，数据集无法下载，是否可以提供国内可下载的源？
wget https://storage.googleapis.com/chineseglue/tasks/inews.zip

**Comment by brightmart** [comment]
可以下载的呢，你再试一试。你可以直接点击下载的

**Comment by DukeEnglish** [comment]
有时候网速不太好多试试看。特别是晚上的时候。如果有云服务器的话，一般各大厂商他们的速度都不错

**Comment by yang9112** [comment]
好像可以了~thx
