### ISSUE TITLE
CMNLI翻译腔比较重

### ISSUE THREAD

**Issue by yyq90** [CLUEbenchmark/CLUE#55]
举个栗子
{"sentence1": "我想等等伙计们，这太糟糕了", "sentence2": "我要等五分钟-嘿，这是不幸的(由我的亲密朋友造成的)。", "gold_label": "neutral"}

**Comment by DukeEnglish** [comment]
yep, this is really a problem, and we are looking for a good way to construct better corpus. Welcome to propose your advice!

**Comment by policeme** [comment]
@DukeEnglish
 and in the test dataset, it doesn't have label, what's wrong

**Comment by brightmart** [comment]
测试集不提供标签，需要你训练后在上面预测，并提交到测评系统上来 www.CLUEbenchmark.com
