### ISSUE TITLE
请问分类任务上的所有评测得分都是用Acc吗

### ISSUE THREAD

**Issue by RyanHuangNLP** [CLUEbenchmark/CLUE#76]
AFQMC:蚂蚁语义相似度(Acc)；TNEWS:文本分类(Acc)；IFLYTEK:长文本分类(Acc); CMNLI: 自然语言推理中文版; COPA: 因果推断; WSC: Winograd模式挑战中文版; CSL: 中国科学文献数据集

只有前三个任务说明得分是Acc，后面的任务是用什么得分呢，Acc or F1？？

**Comment by YC-wind** [comment]
是的
