### ISSUE TITLE
请问ERNIE网络是用tensorflow 改写的吗？

### ISSUE THREAD

**Issue by leo038** [CLUEbenchmark/CLUE#95]
ERNIE网络的官方开源代码是用paddle实现的， 这里面的ERNIE 代码是用tensorflow实现的 ，请问这个改造是等价的吗？

**Comment by leo038** [comment]
我分析了代码发现ernie的代码和bert的代码一样呀， 是不是搞错了呀？

**Comment by P01son6415** [comment]
原始的ERNIE是用paddle训练的，这里测评前把paddle权重转换到了tf，所以代码是一样的，有差别的是模型权重部分

**Comment by leo038** [comment]
请问模型转换的程序可以提供参考一下吗？

**Comment by P01son6415** [comment]
https://github.com/nghuyong/ERNIE-Pytorch

**Comment by leo038** [comment]
> https://github.com/nghuyong/ERNIE-Pytorch

不是要转为tf吗， 这个是转为pytorch的

**Comment by P01son6415** [comment]
> > https://github.com/nghuyong/ERNIE-Pytorch
> 
> 不是要转为tf吗， 这个是转为pytorch的

参考huggingface的转换脚本改成转到tf的就行

**Comment by leo038** [comment]
> > > https://github.com/nghuyong/ERNIE-Pytorch
> > 
> > 
> > 不是要转为tf吗， 这个是转为pytorch的
> 
> 参考huggingface的转换脚本改成转到tf的就行

好的， 谢谢
