### ISSUE TITLE
WSC模型使用Chinese-wwm-bert预训练模型accuracy只有50%

### ISSUE THREAD

**Issue by viviqi** [CLUEbenchmark/CLUE#96]
WSC模型使用Chinese-wwm-bert预训练模型accuracy只有50%，看发布的基线模型有62%左右，大家有遇到这类精度相差很大的情况吗？求教

**Comment by lonePatient** [comment]
@viviqi 可参考下baseline里面的一些参数数值，正常情况下bert-base模型accuracy在72~76之间左右
