### ISSUE TITLE
wsc的任务为什么怎么提交结果都全是0？

### ISSUE THREAD

**Issue by hengchao0248** [CLUEbenchmark/CLUE#97]
是不是wsc的评测流程挂了啊？

**Comment by lonePatient** [comment]
@hengchao0248评测是没有问题，你看看是否是你的提交格式或者文件名错误，可参考https://www.cluebenchmarks.com/common_problem.html

**Comment by hengchao0248** [comment]
经过在群里确认，wsc的任务的提交文件应该是cluewsc2020_predict.json， 不是wsc_predict.json
